### ISSUE TITLE
Initial README update

### ISSUE THREAD

**Issue by JanSpies82** [COS301-SE-2023/WriteToPdf#1]
Update the readme to contain the following:

- [x] Short description of project (in the format xParadigm - RightToPdf - <Description>)
- [x] Link to project board
- [x] Short description of each team member (MUST contain link to LinkedIn)
- [x] Show git structure
- [x] Show organisation & management
- [x] Show branching strategy  
- [x] Code coverage badge
- [x] Build badge
- [x] Requirements badge
- [x] Issue tracking badge
- [x] Monitoring badge

**Comment by JulianPienaar** [comment]
The readme is complete
