### ISSUE TITLE
Solve or dismiss backend dependabot alerts

### ISSUE THREAD

**Issue by JanSpies82** [COS301-SE-2023/WriteToPdf#154]
- [ ] [Server-Side Request Forgery in Request](https://github.com/COS301-SE-2023/WriteToPdf/security/dependabot/8)
- [ ] [Insufficient Granularity of Access Control in JSDom](https://github.com/COS301-SE-2023/WriteToPdf/security/dependabot/7)
- [ ] [Cross-site Scripting in quill](https://github.com/COS301-SE-2023/WriteToPdf/security/dependabot/6)
- [ ] [fast-xml-parser regex vulnerability patch could be improved from a safety perspective](https://github.com/COS301-SE-2023/WriteToPdf/security/dependabot/9)

**Comment by JanSpies82** [comment]
@JulianPienaar @dylankapnias-uni Any update on this?

**Comment by jakeweatherhead** [comment]
I have fixed over half of the backend vulnerabilities by npm uninstalling node-quill-converter

**Comment by jakeweatherhead** [comment]
The moderate severity word-wrap vulnerability was fixed by updating the word-wrap package to v1.2.4 which is the first version to have a patch for the vulnerability in question.

**Comment by jakeweatherhead** [comment]
3 vulnerabilities were removed by updating fast-xml-parser to version 4.2.5 within the "node_modules/@aws-sdk/client-sts" package

**Comment by jakeweatherhead** [comment]
All vulnerabilities are now fixed in the backend on branch: dev/ckeditor after updating all semver packages to minimum of v6.3.1
