### ISSUE TITLE
Implement pdf import

### ISSUE THREAD

**Issue by JanSpies82** [COS301-SE-2023/WriteToPdf#213]
@JanSpies82, so I've decided to completely remove the export to text file feature. Looking at our app, and our usecases, we're called WriteTo**PDF**. We also incorporate images and tables into our document, even though it was great for demo 2, text files are not suitable for the continued intelligent use for our app.

I've linked an image from a quick google search, showcasing why text files aren't a good way to go.

<img width="730" alt="Screenshot 2023-07-18 at 12 33 50" src="https://github.com/COS301-SE-2023/WriteToPdf/assets/36567914/77a77d06-216b-4f58-9668-201b33db82ce">

Closing this issue, and opening another one to focus on PDF conversion of our current editor's exported contents.

_Originally posted by @ConradStras in https://github.com/COS301-SE-2023/WriteToPdf/issues/211#issuecomment-1639975612_
            
This all makes sense. The thing is we need a way to share documents. I don't just mean pdfs, also the editable documents. The reason why txt was useful for this was that the user could export their document as a txt file, and the other user could import it again on their account as a txt. If we choose to only focus on pdf, then we will need a way to import pdfs as well which I think will not be as easy (I could be wrong though). So just something to keep in mind.

**Comment by ConradStras** [comment]
@JanSpies82, yeah totally. But currently export is linked to the frontend branch's button that says "export." Not, "share." Since our app contains images, and tables (i.e. _not_ plain text) exporting text between shared documents becomes superfluous. We should rather export the document's html, and send that as the shared content upon sharing a document.

**Comment by ConradStras** [comment]
@JanSpies82, and @JulianPienaar this is going to be difficult. We might need to get creative to achieve this, and it will probably need to be done on the backend. It can be done on the frontend, but with a WebAssembly approach. That approach is thus not very feasible.

So we'll have to chat with the backend engineers about this, and what's possible.

Libraries we can use:
- PDF.js (can be done browser side, but allows for viewing of PDFs only - which could be useful if we want to view PDFs - we don't have this functionality and it sounds like a nice-to-have.)
- pdf2htmlEX -> Will have to be hosted on the backend if we use this, the other route is web assembly, which is not really feasible.
