### ISSUE TITLE
Table Recognition and Insertion

### ISSUE THREAD

**Issue by ConradStras** [COS301-SE-2023/WriteToPdf#387]
- [ ] Table, text and image tab design and improvement
- [ ] Editable text(recognised text from textract) form UI component
- [ ] Table UI Component (probably max 10 rows and 7 columns)
- [ ] Copy buttons for each UI component
- [ ] Scrollable cells, like excel
- [ ] Establish table row and column limits -> to prevent UI distortion -> see other issue.
- [ ] Text copied to text UI component
- [x] Exporting recognised table to html (simple html - just html tags, no angular fluff.
- [ ] Converting HTML into some type of typescript variable and rendering that in the UI table

**Comment by JanSpies82** [comment]
@ConradStras What is the progress of this issue?
